[tool.ruff]

# Same as Black.
line-length = 88

# Assume Python 3.8.
target-version = "py38"

[tool.ruff.lint]
# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    "A",
    "ANN",
    "ASYNC",
    "B", # bugbear 
    "C4",
    "COM",
    "DTZ",
    "E", # pycodestyle
    "EM",
    "F", # Pyflakes
    "FA",
    "FLY",
    "I",
    "INT",
    "ISC",
    "NPY",
    "PD",
    "PERF",
    "PGH",
    "PIE",
    "PLC",
    "PLE",
    "PLW",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "S", # Bandit
    "SIM",
    "SLOT",
    "T10",
    "TCH",
    "TID",
    "UP",
    "W", # pycodestyle warnings
    "YTT",
]

# Enabled to allow direct type comparisons using is and is not under E721 (see https://docs.astral.sh/ruff/rules/type-comparison/)
preview = true

# ignore E501 - linelength limit (covered by black except in docstrings) 
# and PD901 - use of df variable name
ignore = ["E501", "PD901", "ANN101"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [".git", "__pycache__", "build", "dist", "source"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Ignore `E402` (import violations) in all `__init__.py` file.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"tests/*" = ["ANN", "S101"]


[tool.coverage.run]
branch = true

include = ["tubular/*"]

omit = [
      "tests/*",
]

[tool.coverage.report]

show_missing = true

fail_under = 80